### ISSUE TITLE
Display emissions data by sector, to give people an idea of the *sources* of emissions in an area

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#236]
CAPE currently displays headline emissions statistics for each council, taken from [the 2005–2019 BEIS dataset](https://www.gov.uk/government/statistics/uk-local-authority-and-regional-carbon-dioxide-emissions-national-statistics-2005-to-2019):

<img width="795" alt="Screenshot 2022-01-10 at 14 36 12" src="https://user-images.githubusercontent.com/739624/148783444-ece6017a-eac9-4404-bf0f-6fe8e48bd260.png">

This data is fine, but doesn’t help visitors understand much about the profile of emissions in the area. It feels like there are three useful things we could help people understand:

1. How does this council’s emissions compare to other councils?
1. Where do these emissions come from?
1. How has this changed over time?

The BEIS dataset includes a sectoral breakdown for each council, each year:

* Grand total
   * Industry total
      * Electricity
      * Gas
      * Other fuels
      * Large industrial installations
      * Agriculture
   * Commercial total
      * Electricity
      * Gas
      * Other fuels
   * Public sector total
      * Electricity
      * Gas
      * Other fuels
   * Domestic total
      * Electricity
      * Gas
      * Other fuels
   * Transport total
      * Road transport (A roads)
      * Road transport (Minor roads)
      * Other

Exposing _some_ of this lower-level data would help visitors understand what _sort_ of emissions a council is dealing with in their area. From there, there’s a chance they might be able to understand _why_ certain decisions have been made in the council’s action plan, or assess _how much_ the council is doing to combat the most prevalent emissions sources in the area.

My instinct is the electricity/gas/other breakdowns are a level lower than most people would need. I wonder whether there’s a way we could exclude them in the default view, but let people drill down to see them, if they wanted?

Finally, I wondered whether replacing the sparkline (which looks the same for every council anyway) with a stacked line chart / area chart, might be a way to expose a lot of historical data in a single visualisation:

![image](https://user-images.githubusercontent.com/739624/148785095-f675e36f-d22f-4cef-9dbe-4efcdbe12dd4.png)

**Comment by ajparsons** [comment]
If adding charts, this might be an opportunity to use the altair theme I use for analysis charts into a service 
 https://github.com/mysociety/notebook_helper/blob/main/charting/theme.py

Otherwise the [data visualisation style guide](https://docs.google.com/document/d/1npp0LQHIwK6CZ1oaTPKvS5zg2ass99e-JvsIU5sTUcE/edit#heading=h.wt8orbfp4hul) has some stuff on the colour and where axis labels should be.

If there is going to be a section on the page that's talking about emissions data, this would also be a good opportunity to include about [the labels for the climate comparisons](https://www.mysociety.org/2022/01/13/new-in-cape-five-different-ways-of-finding-similar-councils/) that are in the database but not used in the comparison tool at the moment.

**Comment by ajparsons** [comment]
Without much tampering with the defaults, could be cleverer and embed legend in the bars with a bit more work. 

![image](https://user-images.githubusercontent.com/8157058/149950380-3a3e5ab4-f814-4a8d-bcfa-60b123e095c4.png)

**Comment by zarino** [comment]
This has been deployed!
