### ISSUE TITLE
Council autocomplete suggestions in top-level nav are hidden below the donate banner

### ISSUE THREAD

**Issue by davea** [mysociety/caps#306]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/4776/151346776-97b149a1-7e0e-4f08-a19f-b4ab4a4707e6.png">

Can see this bug on Safari and Chrome on macOS Monterey.

**Comment by zarino** [comment]
Weird, working here:

<img width="333" alt="Screenshot 2022-01-27 at 13 07 46" src="https://user-images.githubusercontent.com/739624/151365004-627f747d-070f-462f-9bc0-c04b8bd52b7d.png">

I know @lucascumsille made a commit this morning fixing this bug (a second time, weirdly, because I’m sure we fixed it earlier in the week too) – maybe that fix has just now been deployed.

@davea are you still seeing the overflow bug?
