### ISSUE TITLE
[CAPE] Better non-expert facing language

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#434]
CAPE’s largest user group at the moment is ordinary members of the public - but this is a group the site is not well set up to cater for. It is missing handholding about what the site contains, our general theory about the importance of local government, and sign-posts to what we think people should do. For instance, the headline on the homepage could be:

![image](https://user-images.githubusercontent.com/8157058/194851072-5b1d673b-45ba-4718-976f-51f3ed61f479.png)

Questions we could be giving answers to:

- What is a climate emergency?
- What is a ‘whole area pledge’?
- But even bigger than that, what does the local government do?
- What’s the relationship between citizens and councillors?
- What’s the relationship between councillors and council ‘officers’?
- What are these climate assemblies I’m hearing about?
- I think we’ve got an election coming up next year, and my council doesn’t have a plan. Is there a website I can use to find out who my councillors are and write to them to say I am concerned by this?

**Comment by ajparsons** [comment]
https://research.mysociety.org/html/joining-up/ would be a good guide to some of the stuff

**Comment by ajparsons** [comment]
Also something not to do (covered a bit above talking about citizens) - that people are important 

https://twitter.com/Bankfieldbecky/status/1580562526575554560

**Comment by JenMysoc** [comment]
We would like @MyfanwyNixon to spend some time assessing the site and specifically considering changes that could be made to:

- [ ] Public facing language
- [ ] explanations of theory of change
- [ ] how could we change the content
- [ ] what could we do to bring in more people and help them use the site

**Comment by MyfanwyNixon** [comment]
Here's a first pass through the site, from the POV of a layperson: https://docs.google.com/document/d/12WZob0F9Xsfi4H_y23097Scek0RRUqab8kUPWpXsRwo/edit#

Next I'll progress that into a list of actual actions.

**Comment by MyfanwyNixon** [comment]
Actions coming out of the document above - of course, these are not set in stone, but should be useful as a basis for discussion:

 **Redesign of homepage**
This to include:
- [ ]  New name for the site
- [ ] Explanatory strapline if the name doesn't do everything on its own
- [ ] An immediate way of explaining what you can do on the site and why that's relevant to the visitor. That _could_ be a video (but also, see the final section of this comment).
- [ ] Links to new pages which we can use to explain concepts in more depth - either in text or video, or both. Might also include reworked versions of the pages we already made for journalists, campaigners etc, that would now take the new data and functionality into account and have clearer calls to action (also, see the final section of this comment).


**Council pages**
These are already slated for a redesign. It should take into account:
- [ ] More space for novice-friendly terminology and explanations around every piece of data - see [this part of the doc](https://docs.google.com/document/d/12WZob0F9Xsfi4H_y23097Scek0RRUqab8kUPWpXsRwo/edit#bookmark=id.jt2d9n5zl6bt)
- [ ] Ways to explain what you might go on to do with this data

**Feature landing pages**
eg https://data.climateemergency.uk/features/good-public-health/

- [ ] Add an introduction which explains what information is on the page, and what people can do with it
- [ ] Delete the columns that are irrelevant, ie 'has a plan' and 'declared an emergency'
- [ ] Ideally, change the links so that they at least go tot he Scorecards part of the council page

**Emissions reduction projects page**
If this isn't already due a redesign or to be integrated differently, this page also needs:

- [ ] An introductory explanation focusing on how to use the information
- [ ] Ideally, links to the actual projects

**'Our data' page**

- [ ] Complete rewrite with the content reordered in a way that makes sense, and copy to help people understand what it is /how they might use it

**Overall**
I'd love to come up with a way that makes people want to explore the site and take the actions we're planning on integrating, like writing to your councillors.

Can we offer any incentive for people who work through a kind of short online 'course' - which would be a mixture of videos, explainers and exercises that set them doing things like finding out their own council's plans in certain areas? At the end we could generate a certificate for them to download. I'm thinking about the [GDPR training I did with Futurelearn](https://www.futurelearn.com/courses/general-data-protection-regulation), which did exactly this.

This is a kind of lightweight version of the incentive CE UK used to mobilise their volunteer markers of CAPs: you promise them upskilling in return for their time.

**Comment by ajparsons** [comment]
Does this ticket need a bit of clarification on the bits that only lucas can do, and what we want there? (Which I think is mostly the very structural stuff?)

**Comment by ajparsons** [comment]
Generally, we've made progress on this, and have added more descriptions in more places. It is easier to tweak and add extra text if we feel we need to. Going to close this one.
