### ISSUE TITLE
Council pages for 2023 Scorecards

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#515]
Almost the same content and layout as last year’s council page, with a few tweaks. Full page description from top to bottom:

### Hero

Council name and type, in the hero, as on the 2022 council pages.

### “About this council” section

If this council was _also_ marked in the 2022 Plan Scorecards, their 2022 Plan Scorecards score and a link to their 2022 Plan Scorecards page should be added to the "About this council" section.

### “About the scoring” section

Wording changes TBC by CEUK.

This may also include a "Key definitions" list, with definitions of terms like "score" and "weighting", with a link to the Methodology for more info.

### “Scorecard section performance” section

Same as last year – a table with a row per section, and a column for the section name, this current council’s score, and the average score across councils of the current type.

**Note** Combined Authorities have different sections to the other council types, so we need to handle that.

### “Individual question performance” section

Add controls to allow filtering the table to show only questions that:

- Were marked from a particular source (FOI / volunteer / national data / volunteer + national data)
- Are "council operations only"

Then a table of questions for this council, with a row per question (grouped into sections, like the current fold-out question table on the single council page) and columns for question number, question text (with link to show criteria), question source (see above), question weighting, this council’s score on each question/section, score for a chosen comparison council, number of councils of the same type who got full marks.

**Note** that this means there still needs to be a way to add up to 1 additional council to compare, as a new column, in this table (as on the 2022 council pages).

**Note** that a small number of the questions will be scored with negative marks!! For these questions, the marks will be displayed as either:

- “No negative points awarded” (instead of “0” which could be misunderstood)
- “-1” / “-2” / “-3” (if negative points awarded)

**Note** that the table won’t have `.subpoint-question` rows any more – just collapsible sections, with a single level of questions inside.

**Comment by lucascumsille** [comment]
Almost the same content and layout as last year’s council page, with a few tweaks. Full page description from top to bottom:

### Hero

- [ ] Council name and type, in the hero, as on the 2022 council pages.

### “About this council” section

- [ ] If this council was _also_ marked in the 2022 Plan Scorecards, their 2022 Plan Scorecards score and a link to their 2022 Plan Scorecards page should be added to the "About this council" section.

### “About the scoring” section

Wording changes TBC by CEUK.

- [ ] This may also include a "Key definitions" list, with definitions of terms like "score" and "weighting", with a link to the Methodology for more info.

### “Scorecard section performance” section

- [ ] Same as last year – a table with a row per section, and a column for the section name, this current council’s score, and the average score across councils of the current type.


**Note** Combined Authorities have different sections to the other council types, so we need to handle that.

### “Individual question performance” section

- [ ] Add controls to allow filtering the table to show only questions that:
  - [ ] Were marked from a particular source (FOI / volunteer / national data / volunteer + national data)
  - [ ]  Are "council operations only"


- [ ] Then a table of questions for this council, with a row per question (grouped into sections, like the current fold-out question table on the single council page) and columns for question number, question text (with link to show criteria), question source (see above), question weighting, this council’s score on each question/section, score for a chosen comparison council, number of councils of the same type who got full marks.

- [ ] **Note** that this means there still needs to be a way to add up to 1 additional council to compare, as a new column, in this table (as on the 2022 council pages).

- [ ] **Note** that a small number of the questions will be scored with negative marks!! For these questions, the marks will be displayed as either:


- [ ] “No negative points awarded” (instead of “0” which could be misunderstood)
- [ ] “-1” / “-2” / “-3” (if negative points awarded)


- [ ] **Note** that the table won’t have `.subpoint-question` rows any more – just collapsible sections, with a single level of questions inside.

**Comment by lucascumsille** [comment]
@zarino for
>Note Combined Authorities have different sections to the other council types, so we need to handle that.

Just to clarify I assume that just like last version, we won't be allowing users to compare a ST with a CA?

**Comment by zarino** [comment]
> Just to clarify I assume that just like last version, we won't be allowing users to compare a ST with a CA?

@lucascumsille Yeah, it wouldn’t make sense to allow direct comparisons of Single Tiers and Combined Authorities – they’re very different types of authority, with very different responsibilities.

My note above was just to remind us that the names and number of sections will be different on a Combined Authority’s page than on the page for any other type of council.
