### ISSUE TITLE
Nice to have Scorecards 2023

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#545]
### General

- [x] Make the focus state more obvious
- [x] Navbar hover and focus state more obvious.
- [x] Main navbar with a light gradient
![Screenshot 2023-08-29 at 17-01-32 Council Climate Plan Scorecards](https://github.com/mysociety/caps/assets/13790153/37bbe575-a6fd-468f-a7ed-8c2527a7bd12)

### Homepage

- [ ] Enable mobile view for sections on home table
- [ ] Consider stronger visual “connection” between homepage table jump/filter controls and the table itself

### Council page
- [ ]  When applying filter and there are no results, we probably want to display a message.
- [x]  When the accordion button is active, I should change the colour to make it obvious that the state is different.
- [x]  I left some TODO for Struan, things like if the question is council operational only do this. Or add classes to the row.
- [ ] Add highlights sections. For example "This council is a top scorer in "Biodiversity""
- [ ] Add a political control message for council that change on 2023.

### Section child page

- [ ] Way to travel to another section

**Comment by zarino** [comment]
FYI @lucascumsille here’s something I was playing with earlier, when I was trying to create a clearer visual connection between the homepage council type filters / "jump to council in table" search input, and the table itself…

![Screenshot 2023-09-28 at 08-13-33 Council Climate Plan Scorecards](https://github.com/mysociety/caps/assets/739624/8e83b48a-62d0-475e-96e4-1ec9e2cc403f)

My thought process: Exploring "tabs" as a way to represent the different council type tables (rather than little buttons), and then moving the "jump to council" search box nearer the table itself, near to the advanced filters, since those all feel like actions you take on the table. This left me with the "external" links to the sections page and a council’s individual page, which I—perhaps controversially—ended up moving down to the bottom, alongside a "card" for the (paid-for) spreadsheet download offer.

Would be interesting to discuss with CEUK, see whether they feel this is an improvement over what we have at the moment.

**Comment by lucascumsille** [comment]
I mean I like it, but my instant thought is: are people going to scroll down and see it? I think if we are going to make this changes it would also mean to access all the items below in the navbar. But last time I remember Isaac wasn't keen on putting the section there. 
If we are not including them in the navbar, then adding a content navbar stick to the bottom, potentially one that could be opened or closed could be an approach.

I feel like we are back to the discussion from the vert begining and having a scorecard table page, and leaving the homepage as a way to present the project and main features, but CEUK wasn't too keen for that.
