### ISSUE TITLE
Update static text on non-static pages for Scorecards 2023

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#577]
CEUK have provided bits of static text for the various static parts of the homepage, council page, and section page(s).

**Comment by lucascumsille** [comment]
Thanks Zarino
Copy here: https://docs.google.com/document/d/1EwjPIxytoEqlS0UmzP0KCrF-kMbZI37wIfnei8-t2uM/edit

**Comment by lucascumsille** [comment]
- [ ] There is no way to get to a section page (eg: /sections/s1_b_h/) or the overall Sections page (/sections/) from the homepage. The purple "Go to sections" button at the top centre of the homepage doesn’t work.
- [ ] /sections/ doesn’t currently show a table, by default, on pageload. My instinct is this page should work like the homepage, it should "select" the Single Tier button by default, until the user chooses otherwise.
- [ ] We’re obviously missing section descriptions on /sections/ page.
- [ ] It felt not very obvious to me that you could click the entire "cards" on the /sections/ page. I think because they don’t react when you hover over them, and there’s no call to action (underlined link or button) inside the card to suggest that you even should hover near them.
- [ ] /scorecards/ is missing a page title (browser just displays: | Council Climate Scorecards)
- [ ] We’re obviously missing text content for the "Section information" accordion on /sections/<whatever>/.
- [ ] Like /sections/, /sections/<whatever>/ doesn’t currently show a table, by default, on pageload. As above, I think this page should behave like the homepage, with the "Single Tier" button pre-selected (or "Combined Authority" if this is a section that only applies to CAs), until the user chooses otherwise.
- [ ] When you "select" a council type button under "show questions by type of council" on /sections/<whatever>/, the button doesn’t display as "active".
- [ ] Even worse, when you click that council type button, the entire page reloads and you’re left staring at the top of the new page, while the table of questions is (in my case) at least two full page scrolls down below. Yuck.
- [ ] The markup for question rows inside the question table on /sections/<whatever>/ isn’t the same as the markup for question rows on /councils/<whatever>/. As a result, the wording for each question on /sections/<whatever>/ crashes into the "How this is marked" button below, because the question wording is wrapped in a <div class="js-collapse-children"> (rather than just the <p> used for questions on the council page). I’m getting serious [code smell](https://en.wikipedia.org/wiki/Code_smell) from the fact that these two tables don’t appear to be reusing a common template for rendering these rows – or at least the content of this particular cell!

**Comment by lucascumsille** [comment]
@Zarino Regarding the page on load behaviour:
>/sections/ doesn’t currently show a table, by default, on pageload. My instinct is this page should work like the homepage, it should "select" the Single Tier button by default, until the user chooses otherwise.
and
>Like /sections/, /sections/<whatever>/ doesn’t currently show a table, by default, on pageload. As above, I think this page should behave like the homepage, with the "Single Tier" button pre-selected (or "Combined Authority" if this is a section that only applies to CAs), until the user chooses otherwise.

I remember we had this discussion in the past with the methodology page, and when I initially would display the content/questions having the content for single tier councils by default. I was asked to change it to display nothing till there is a selection, basically forcing the user to pick something. The logic behind was:

- Climate emergency didn't want users to be getting information about councils that don't apply to them, because they had missed the filter or not be bothered into make a selection because there is already something being displayed.

Unlike the homepage we are not seeing council names, so I think is more likely will have a user staying with default view(Single tier), I  can imagine this happening with a CA viewer for example. Now this might not be many cases and I get that in the methodology page we are dealing with more rules that apply to X council and not to Y council, so having a default view could be the best for the majority.

**Comment by lucascumsille** [comment]
### Home page

### Council page

- [ ] Link to See this council’s 2021 Plan Scorecard button
- [ ] Link You can check out how this council scored in the Plan Scorecards
- [ ] Clear All filter not working
- [ ] Council under review message. Need to add conditional to be shown when needed.

**Comment by struan** [comment]
I have done the first one is the small fixes branch.

**Comment by struan** [comment]
Also, the section description things are done in #580

**Comment by lucascumsille** [comment]
Sorry @struan I know I had told you that we would follow the same behaviour as the methodology page. But yesterday with @zarino decided to display Single tier by default. 

> Like /sections/, /sections/<whatever>/ doesn’t currently show a table, by default, on pageload. As above, I think this page should behave like the homepage, with the "Single Tier" button pre-selected (or "Combined Authority" if this is a section that only applies to CAs), until the user chooses otherwise.

My thought in order to prevent:
>Even worse, when you click that council type button, the entire page reloads and you’re left staring at the top of the new page, while the table of questions is (in my case) at least two full page scrolls down below. Yuck.

It would be to add an ID to the table section, and add that id to the buttons. For example `{% url 'scoring:section' section.code %}?type=county/#table-id`

For this issue:
> When you "select" a council type button under "show questions by type of council" on /sections//, the button doesn’t display as "active".

Is it too much hassle to add a body class like `single-tier` `combined`? that way controlling the active effect via CSS would be quite simple. I think we could achieve it with JS, but probably it would have less hassle with Django.

**Comment by zarino** [comment]
Fixes for most of this ticket have already been deployed, and the remainder has been moved into https://github.com/mysociety/caps/issues/586.
