### ISSUE TITLE
[scorecards] update filtering to enable spliting metro and non metro districts

### ISSUE THREAD

**Issue by struan** [mysociety/caps#611]
There's been a request from a council officer that this would be a helpful distinction to be able to make.

**Comment by zarino** [comment]
Just added a Django filter that allows splitting the "District" scoring group into councils with an `authority_type` of either `MD` or `NMD`, only to spend an hour trying to diagnose why it wouldn’t work.

Turns out, the "District" scoring group is _only_ `NMD` councils. `MD` councils are one of the council types in the "Single Tier" scoring group 🐵 

Will look at the code to see how (if!) we’ve handled this for other filters, which apply to different scoring groups…
