### ISSUE TITLE
Homepage could have lookup by council name

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#88]
Currently the homepage does lookup by postcode, but users may also want to look up a council they don't know the postcode for.

For instance, if you're a council worker who lives out of area, you might not be able to simply find your own council. Or if you have been told to look at a specific plan, have to click off page to find the link. 

IMD maps website has a version with two textboxes and an auto-complete on the 'short' version of the council name https://research.mysociety.org/sites/imd2019/

**Comment by zarino** [comment]
Leaving some notes here for when this ticket eventually gets picked up.

Would be nice to display council name suggestions in some sort of autocomplete, as @ajparsons mentions. Ideally one with good accessibility. I think we used https://github.com/alphagov/accessible-autocomplete for this in FixMyStreet.

Council name autocomplete suggestions could kick in once you’ve typed 3 a-z characters (since, if it’s a postcode, [it’d have a number in the first three characters](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation)).

**Comment by zarino** [comment]
https://research.mysociety.org/sites/imd2019/ uses https://projects.verou.me/awesomplete/ – https://github.com/mysociety/imd2019/blob/5824d5d4d9cd558f720bfbea490ac950ea784e7e/templates/imd2019/home.html#L103-L132
